name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --filter Category!=Integration --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release -o finalpackage --no-build
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: nupkg
        path: finalpackage
    - name: Push Nupkg to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
          nupkg-path:  './**.nupkg'
          repo-owner:  'perokvist'
          gh-user:  'perokvist'
          token:  ${{ secrets.GITHUB_TOKEN }}
          
    - uses: actions/setup-dotnet@v1
      with:
        source-url: https://api.nuget.org/v3/index.json
      env: 
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
    - name: Push to nuget
      run: dotnet nuget push ./artifacts/**.nupkg --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}}
      
